### ISSUE TITLE
Challenge is 'None'

### ISSUE THREAD

**Issue by MitchK** [TracyWebTech/django-conversejs#9]
Hi,

I'm trying out the boshclient.py and I get the following error:

`(venv)PALM00545424A:conversejs i841712$ python boshclient.py http://localhost/http-bind username@localhost password
Traceback (most recent call last):
  File "boshclient.py", line 335, in <module>
    print c.get_credentials()
  File "boshclient.py", line 313, in get_credentials
    success = self.authenticate_xmpp()
  File "boshclient.py", line 271, in authenticate_xmpp
    response = sasl.process(base64.b64decode(challenge))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 73, in b64decode
    return binascii.a2b_base64(s)
TypeError: must be string or buffer, not None`

**Comment by fpytloun** [comment]
Same issue here. Anyone found solution?
